name: myapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: any
  intl: any
  simple_animations: any
  hive: any
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  uuid: any
  percent_indicator: any
  image_picker: any
  provider: any
  google_fonts: any
  flex_color_picker: any
  flutter_colorpicker: any
  flutter_staggered_animations: any
  fl_chart: any
  rive: any
  shared_preferences: any
  url_launcher: any
  json_annotation: any
  syncfusion_flutter_gauges: any
  path: any
  smooth_page_indicator: any
  freezed_annotation: any
  table_calendar: any
  http: any
  flutter_html: any
  flutter_local_notifications: any
  timezone: any
  timeline_tile: any
  flutter_native_splash: any
  permission_handler: any
  firebase_core: any
  firebase_ai: any
  hive_generator: ^2.0.1
  build_runner: ^2.4.13

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: any
  json_serializable: any
  freezed: any
  flutter_launcher_icons: any

flutter:
  uses-material-design: true

  assets:
    - assets/acuario/
    - assets/luna_png/
    - assets/icons/

flutter_launcher_icons:
  android: "launcher_icon" # Can be true or a path to the icon image
  ios: true
  image_path: "assets/icons/icon.png"
  web: 
    generate: true
    image_path: "assets/icons/icon.png"
  windows:
    generate: true
    image_path: "assets/icons/icon.png"
  macos:
    generate: true
    image_path: "assets/icons/icon.png"

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#000000"
  image: assets/luna_png/luna_splash_w.png
  image_dark: assets/luna_png/luna_splash_b.png

  android_12:
    color: "#FFFFFF"
    color_dark: "#000000"
    image: assets/luna_png/luna_splash_w.png
    image_dark: assets/luna_png/luna_splash_b.png
